log/log/urls.py
from django.contrib import admin
from django.urls import path
from dailylog.views import Home, SignUp, LogListView, QuestionCreateView, LogDetailView, log, save_log
from django.contrib.auth import views as auth_views
# from dailylog.views import views

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('create/log', log, name='create_log'),
    path('save/log', save_log, name='save_log'),
    path('log/<int:pk>/', LogDetailView.as_view(), name='log_detail'),
    path('logs', LogListView.as_view(), name='logs'),
    path('create/question', QuestionCreateView.as_view(), name='create_question'),
    path('login', auth_views.LoginView.as_view(template_name='auth/login.html', success_url = 'logs'), name='login'),
    path('signup', SignUp.as_view(), name='signup'),
    path('admin/', admin.site.urls),
]

log/dailylog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    text = models.TextField()
    question_type = models.TextField()
    default = models.BooleanField()

    def __str__(self):
        return f'Question Text: {self.text} Question Type: {self.question_type}'

class Log(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=True)
    questions = models.ManyToManyField(Question, through='Answer')

    def __str__(self):
        return f'Created: {self.created}'

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    log = models.ForeignKey(Log, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return f'Question: {self.question.text} Answer: {self.text}'

log/dailylog/views.py
from django.shortcuts import render
from dailylog.models import Log, Question, Answer
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView, View
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponseRedirect
# Create your views here.


def log(request):
    return render(request, 'log/create_log.html', {'questions': Question.objects.all()})

def save_log(request):
    log = Log.objects.create(user_id = request.user.id)
    for key, value in request.POST.dict().items():
        if key == 'csrfmiddlewaretoken':
            continue
        # Create Answer
        answer = Answer.objects.create(log_id = log.id, question_id = int(key[:len(key)-1]), text = value)

    return HttpResponseRedirect('/log/' + str(log.id))

class LogDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login'
    redirect_field_name = 'redirect_to'
    template_name = 'log/detail.html'

    model = Log

class Home(TemplateView):
    template_name = "home.html"

class LogListView(LoginRequiredMixin, ListView):
    login_url = '/login'
    redirect_field_name = 'redirect_to'
    template_name = 'log/list.html'

    def get_queryset(self):
        return Log.objects.filter(user = self.request.user)


class QuestionCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login'
    redirect_field_name = 'redirect_to'
    template_name = "question/create.html"
    model = Question
    fields = ['text', 'question_type', 'default']
    success_url = '/create/question'

class SignUp(CreateView):
    model = User
    fields = ['username', 'password']
    template_name = 'auth/signup.html'
    success_url = 'login'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.set_password(form.cleaned_data['password'])
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

log/dailylog/templates/base.html
<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
</head>

  <nav>
    <div class="nav-wrapper">
      <a href= {% url 'create_log' %} class="brand-logo">Make Your Log</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href = {% url 'home' %}>Home</a></li>
        <li><a href = {% url 'logs' %}>Logs</a></li>
        <li><a href = {% url 'create_question' %}>Create Question</a></li>
      </ul>
    </div>
  </nav>

<body>
    <div class="container center-align">
      <div>
          <h1>Log It All</h1>
      </div>
        {% block content %}
        {% endblock %}
    </div>
</body>

<foot>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
</foot>

log/dailylog/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col s6">
    <a href="/login" class="waves-effect waves-light btn"> Log In </a>
  </div>
  <div class="col s6">
    <a href="/signup" class="waves-effect waves-light btn"> Sign Up </a>
  </div>
</div>
{% endblock %}

log/dailylog/templates/log/create_log.html
{% extends "../base.html" %}

{% block content %}


<form method="post" action="/save/log?pdb">
  {% csrf_token %}
  {% for question in questions %}
    <div>
      {{ question.text }}
    </div>
    <div>
      <input name = {{ question.id }}/>
    </div>
  {% endfor %}
  <p>
    <button class="waves-effect waves-light btn" type="submit">Create Question</button>
  </p>
</form>

{% endblock %}

log/dailylog/templates/log/detail.html
{% extends "../base.html" %}

{% block content %}

{{ object }}
<table>
<tr>
  <td>
    Question
  </td>
  <td>
    Answer
  </td>
</tr>
{% for answer in object.answer_set.all %}
  <tr>
    <td>
    {{ answer.question.text }}
    </td>
    <td>
     {{ answer.text }}
    </td>
  </tr>
{% endfor %}

</table>

{% endblock %}

log/dailylog/templates/log/list.html
{% extends "../base.html" %}

{% block content %}

<table>
  <tr>
    <td>
      Log Date
    </td>
  </tr>
{% for log in object_list %}
  <tr>
    <td>
      <a href = {% url 'log_detail' log.id %}>
        {{ log }}
      </a>
    </td>
  </tr>
{% endfor %}
</table>

{% endblock %}

log/dailylog/templates/question/create.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="{% url 'create_question' %}">
  {% csrf_token %}
  <div>
      <div>Question Text</div>
      <div><input name="text"/></div>
  </div>
  <div>
      <div>Type - Binary/Likard/Text </div>
      <div><input name="question_type"/></div>
  </div>
  <div>
      <div>Should this be a default question? </div>
      <div><input name="default" type="integer"/></div>
  </div>

  <p>
    <button class="waves-effect waves-light btn" type="submit">Create Question</button>
  </p>
</form>

{% endblock %}